DROP TABLE PythonConnDB.FilePaths;
DROP TABLE PythonConnDB.DocObjs;
DROP TABLE PythonConnDB.LinkObjs;
DROP DATABASE PythonConnDB;
DROP USER 'LVRSPAdmin'@'localhost';

CREATE DATABASE PythonConnDB;

USE PythonConnDB;

CREATE TABLE FilePaths(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    path TINYTEXT NOT NULL,
    entityId INTEGER NOT NULL,
    CONSTRAINT paths_PK PRIMARY KEY (ID)
);

CREATE TABLE DocObjs(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    title TINYTEXT NOT NULL,
    metadata TEXT,
    entityId INTEGER NOT NULL,
    numLinks INTEGER NOT NULL,
    CONSTRAINT docs_PK PRIMARY KEY (ID)
);

CREATE TABLE LinkObjs(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    fromTitle TINYTEXT NOT NULL,
    toTitle TINYTEXT NOT NULL,
    CONSTRAINT links_PK PRIMARY KEY (ID)
);

CREATE USER 'LVRSPAdmin'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
GRANT CREATE, ALTER, DROP, INSERT, UPDATE, INDEX, DELETE, SELECT, REFERENCES, LOCK TABLES ON *.* TO 'LVRSPAdmin'@'localhost';

CREATE USER 'LVRSPPython'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
GRANT CREATE, ALTER, DROP, INSERT, UPDATE, INDEX, DELETE, SELECT, REFERENCES, LOCK TABLES ON PythonConnDB.* TO 'LVRSPPython'@'localhost';
FLUSH PRIVILEGES;